name: pratique exam CICD

on: [push]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Flask app (test)
        run: |
          python main.py

      - name: Generate report
        run: |
          echo "## Rapport CI/CD" > report.md
          echo "Application exécutée avec succès." >> report.md
